name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Use the Node.js version required by your project

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to Vercel
      run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
        VERCEL_ORG: ${{ secrets.VERCEL_ORG }}

    - name: Check Deployment
      run: curl -I $(npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --output-only)
